[package]
name = "crosses-utils"
version = "0.1.0"
edition = "2021"

[features]
default = [ "serde" ]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }

